--Vide les tables
DELETE FROM TPIECE;
DELETE FROM TTYPE_PIECE;
--Encode les données dans la base de données de test
--TTYPEPIECE
INSERT INTO TTYPE_PIECE (CODE_TYP, NOM_TYP, HUMIDE_TYP) VALUES('SALON','Salon',false);
INSERT INTO TTYPE_PIECE (CODE_TYP, NOM_TYP, HUMIDE_TYP) VALUES('LIVING','Living',false);
INSERT INTO TTYPE_PIECE (CODE_TYP, NOM_TYP, HUMIDE_TYP) VALUES('SDB','Salle de bain',true);

--TPIECE
INSERT INTO TPIECE (NUM_PIE, NOM_PIE, DESCRIPTION_PIE, ETAGE_PIE, FKTYPE_PIE, FKINSTALLATION_PIE)
OVERRIDING SYSTEM VALUE
VALUES(1, 'SALON_MAB', 'Mon Salon', 1.0, 'SALON', 1);
